### ISSUE TITLE
Why transpose is not necessary when previous layer is not conv?

### ISSUE THREAD

**Issue by misssprite** [conanhujinming/matcaffe2caffe#1]
Thank you for your convenient tool!

I have a question on the following line.
No matter what type the previous layer is, `InnerProduct` have a two-dimensional weight matrix. Why skipping transposing here?
https://github.com/conanhujinming/matcaffe2caffe/blob/51048e9c9c2fc2a1109a7bdac71e51a13e9e77d7/matcaffe2caffe.py#L80-L82

**Comment by conanhujinming** [comment]
Thank you for your question. Sorry for the late reply. For the `matcaffe`, the stored weights of `InnerProduct` is somehow not column-major, unless the previous layer is a conv layer. Sorry that I am not an expert of `MATLAB` and I do not know the reason. But I just figure out it works like this so I skip transposing here.
