### ISSUE TITLE
Problem with PNet and RNet conversion

### ISSUE THREAD

**Issue by WIll-Xu35** [conanhujinming/matcaffe2caffe#2]
Hi all,

I used this tool to convert matcaffe trained model to pycaffe model. The converted ONet model can work properly but not PNet or RNet.

The converted PNet and RNet still needs transposed image to produce the correct output. It seems that they are not converted at all.

Anyone has any idea what may have caused this?

Thanks

**Comment by conanhujinming** [comment]
Hi, I think the MTCNN model in this repo can be successfully converted. Can you somehow provide your model (or link) and other things like test data? Thanks.

**Comment by WIll-Xu35** [comment]
Thank you for your reply. I've gone through the whole process again and it is now working as expected.

Thank you for sharing your awesome work!

**Comment by WIll-Xu35** [comment]
@conanhujinming  Hi, can I ask an off-topic question about caffemodel conversion?

I trained a model using BGR image(since opencv reads images in BGR order), the result is good and when I want to deploy it, the input somehow has to be in RGB order. Is there any method to modify the model to take input of RGB order and still outputs the exact same result?

The model is not complicated, only contains convolution, innerproduct, max pooling and PRelu.

Many thanks.

**Comment by conanhujinming** [comment]
Hi, I think you can try to transpose the weights of filters in the dimension of channels. Maybe you can try to do this based on my code: just change the weights where I change them. I am not quite sure about it but I guess it may work.

**Comment by WIll-Xu35** [comment]
@conanhujinming Thank you for your reply.

I reconsidered this and found that only modifying the weights of the first conv layer will suffice. Just switch the weights channels as you mentioned. The rest of the networks' weights should be unchanged. I'll try to implement this base on your code.

Thank you again for your advice.

**Comment by conanhujinming** [comment]
Well, I don't think modifying the first conv layer would be sufficient. I guess all the conv layers before the first FC layer should be modified. You can have a try. I guess it is not so difficult to implement. Good luck.
